name: Push git

on:
  push:
    branches:
      - main

jobs:
  keren:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install
      
      - name: Deploy to VPS
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            node -v
            cd /home/diagnify/apps/chatbot-service
            git pull origin main
            npm ci
            pm2 restart chatbot-service
        
        
        
